name: bump-container
description: Dereference a container registry pointer tag such as as latest
author: Simon Li
inputs:
  repo:
    required: true
    description: 'Repository, either `docker.io/<owner>/<repo>` or `quay.io/<owner>/<repo>`'
  pointer:
    required: true
    description: Tag to be dereferenced
    default: latest
  regex:
    required: false
    description: Optional regular expression to match against the tag
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
